# Generated by Django 4.2.24 on 2025-09-04 17:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mekan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('fiyat_araligi', models.CharField(max_length=50)),
                ('konum', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('adres', models.CharField(max_length=250)),
            ],
        ),
    ]
