# Generated by Django 4.2.24 on 2025-09-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biranerde_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mekan',
            name='puan',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mekan',
            name='adres',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
